[package]
name = "square"
version = "0.1.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
description = ""

[package.metadata.bundle.example.hello_world]
name = "Hello World"
identifier = "io.mehcode.square.example.hello_world"

[dependencies]
lazy_static = "1"
palette = { version = "0.4", default-features = false }
yoga-sys = { git = "https://github.com/mehcode/yoga-sys", rev = "4efbc570ccf351dc73273323b653fa1188de88c0" } 

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc_id = "0.1"
cocoa = "0.15"

[profile.release]
codegen-units = 1
lto = true
