[package]
name = "square"
version = "0.1.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
description = ""

[package.metadata.bundle.example.layout]
name = "Layout"
identifier = "io.mehcode.square.example.layout"

[package.metadata.bundle.example.calculator]
name = "Calculator"
identifier = "io.mehcode.square.example.calculator"

[dependencies]
lazy_static = "1"
yoga = "0.2"
fnv = "1.0.3"
parking_lot = "0.6"
downcast = "0.9.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc_id = "0.1"
cocoa = "0.15"
dispatch = "0.1"

[profile.release]
codegen-units = 1
lto = true
